import { createContext, useContext, useState, useEffect } from "react";

// Translations
const translations = {
  fi: {
    // Common
    app_name: "Walleta",
    save: "Tallenna",
    cancel: "Peru",
    delete: "Poista",
    edit: "Muokkaa",
    add: "Lisää",
    close: "Sulje",
    loading: "Ladataan...",
    refresh: "Päivitä",
    back: "Takaisin",
    next: "Seuraava",
    yes: "Kyllä",
    no: "Ei",
    
    // Auth
    login: "Kirjaudu",
    logout: "Kirjaudu ulos",
    register: "Rekisteröidy",
    email: "Sähköposti",
    password: "Salasana",
    name: "Nimi",
    login_title: "Tervetuloa takaisin",
    login_subtitle: "Kirjaudu sisään jatkaaksesi",
    register_title: "Luo tili",
    register_subtitle: "Aloita taloutesi hallinta tänään",
    no_account: "Ei vielä tiliä?",
    have_account: "Onko sinulla jo tili?",
    login_success: "Kirjautuminen onnistui!",
    register_success: "Tili luotu onnistuneesti!",
    invalid_credentials: "Virheellinen sähköposti tai salasana",
    
    // Landing
    hero_title: "Hallitse talouttasi",
    hero_title_highlight: "helposti",
    hero_subtitle: "Walleta auttaa sinua ymmärtämään, hallitsemaan ja parantamaan talouttasi arjessa – ilman stressiä tai monimutkaisuutta.",
    start_now: "Aloita nyt",
    start_free: "Aloita ilmaiseksi",
    no_hidden_fees: "Ei piilokuluja",
    cancel_anytime: "Peru milloin vain",
    features_title: "Kaikki mitä tarvitset",
    features_subtitle: "Walleta kokoaa taloustietosi yhteen paikkaan ja näyttää ne ymmärrettävässä muodossa",
    pricing_title: "Yksinkertainen hinnoittelu",
    pricing_subtitle: "Yksi hinta, kaikki ominaisuudet. Ei piilomaksuja.",
    monthly_subscription: "Kuukausitilaus",
    per_month: "€ / kk",
    includes: "Sisältää:",
    cta_title: "Ota taloutesi haltuun tänään",
    cta_subtitle: "Liity tuhansien suomalaisten joukkoon, jotka jo hallitsevat talouttaan Walletalla.",
    
    // Features
    budgeting: "Budjetointi",
    budgeting_desc: "Aseta kuukausibudjetti ja seuraa toteumaa reaaliajassa",
    expense_tracking: "Menoseuranta",
    expense_tracking_desc: "Lisää kulut helposti ja ryhmittele ne kategorioihin",
    loan_management: "Lainojen hallinta",
    loan_management_desc: "Seuraa asuntolainoja, autolainoja ja muita velkoja",
    savings_goals: "Säästötavoitteet",
    savings_goals_desc: "Aseta tavoitteita ja seuraa edistymistäsi",
    income_expenses: "Tulot & Menot",
    income_expenses_desc: "Näe yhdellä silmäyksellä kaikki rahavirtasi",
    secure: "Turvallinen",
    secure_desc: "Tietosi ovat turvassa vahvalla salauksella",
    
    // Navigation
    nav_overview: "Yleiskatsaus",
    nav_budget: "Budjetti",
    nav_expenses: "Menot",
    nav_incomes: "Tulot",
    nav_loans: "Lainat",
    nav_savings: "Säästöt",
    nav_reports: "Raportit",
    nav_banks: "Pankit",
    nav_settings: "Asetukset",
    
    // Dashboard
    dashboard_title: "Yleiskatsaus",
    dashboard_subtitle: "Tässä kuussa paljonko maksaa elää",
    add_expense: "Lisää kulu",
    monthly_expenses: "Kuukauden kulut",
    active_fixed_expenses: "Aktiiviset kiinteät menot",
    budget_used: "Budjetista käytetty",
    budget: "Budjetti",
    income_remaining: "Tulot & Käteen jäävä",
    net_income_total: "Nettotulot yhteensä",
    remaining: "Käteen jää",
    expenses_by_category: "Kulut kategorioittain",
    loans: "Lainat",
    total_remaining: "Jäljellä yhteensä",
    monthly_payments: "Kuukausierät",
    savings: "Säästöt",
    total_saved: "Säästetty yhteensä",
    target: "Tavoite",
    net_worth: "Nettovarallisuus",
    savings_minus_loans: "Säästöt - Lainat",
    budget_alert_title: "Lähestyt budjettirajaa",
    budget_alert_desc: "Olet käyttänyt {percentage} budjetistasi.",
    
    // Expenses
    expenses_title: "Menot",
    expenses_subtitle: "Kuukauden kulut",
    add_new_expense: "Lisää uusi kulu",
    amount: "Summa",
    description: "Kuvaus",
    category: "Kategoria",
    date: "Päivämäärä",
    select_category: "Valitse kategoria",
    expense_added: "Kulu lisätty!",
    expense_deleted: "Kulu poistettu",
    no_expenses: "Ei kuluja",
    no_expenses_desc: "Lisää ensimmäinen kulusi aloittaaksesi seurannan.",
    
    // Incomes
    incomes_title: "Tulot",
    incomes_subtitle: "Kuukauden tulot",
    add_income: "Lisää tulo",
    add_new_income: "Lisää uusi tulo",
    source: "Lähde",
    select_source: "Valitse lähde",
    recurring: "Toistuva tulo",
    income_added: "Tulo lisätty!",
    income_deleted: "Tulo poistettu",
    no_incomes: "Ei tuloja",
    no_incomes_desc: "Lisää ensimmäinen tulosi aloittaaksesi seurannan.",
    source_salary: "Palkka",
    source_freelance: "Freelance",
    source_investment: "Sijoitukset",
    source_other: "Muu",
    
    // Budget
    budget_title: "Budjetti",
    set_budget: "Aseta budjetti",
    edit_budget: "Muokkaa",
    monthly_budget: "Kuukausibudjetti",
    summary: "Yhteenveto",
    spent: "Käytetty",
    budget_remaining: "Jäljellä",
    usage_rate: "Käyttöaste",
    budget_saved: "Budjetti tallennettu!",
    no_budget: "Aseta kuukausibudjetti",
    no_budget_desc: "Määritä kuukausibudjettisi aloittaaksesi menojen seurannan.",
    
    // Loans
    loans_title: "Lainat",
    loans_subtitle: "Hallitse velkojasi",
    add_loan: "Lisää laina",
    add_new_loan: "Lisää uusi laina",
    loan_name: "Lainan nimi",
    loan_type: "Lainatyyppi",
    original_amount: "Alkuperäinen summa",
    remaining_amount: "Jäljellä",
    interest_rate: "Korko",
    monthly_payment: "Kuukausierä",
    start_date: "Aloituspäivä",
    loan_added: "Laina lisätty!",
    loan_deleted: "Laina poistettu",
    no_loans: "Ei lainoja",
    no_loans_desc: "Lisää laina aloittaaksesi velan seurannan.",
    paid: "Maksettu",
    loan_mortgage: "Asuntolaina",
    loan_car: "Autolaina",
    loan_consumer: "Kulutusluotto",
    loan_student: "Opintolaina",
    
    // Savings
    savings_title: "Säästöt",
    savings_subtitle: "Seuraa säästötavoitteitasi",
    add_goal: "Lisää tavoite",
    add_savings_goal: "Lisää säästötavoite",
    goal_name: "Tavoitteen nimi",
    target_amount: "Tavoitesumma",
    current_amount: "Säästetty",
    target_date: "Tavoitepäivä",
    icon: "Ikoni",
    goal_added: "Säästötavoite lisätty!",
    goal_updated: "Säästötavoite päivitetty!",
    goal_deleted: "Säästötavoite poistettu",
    no_goals: "Ei säästötavoitteita",
    no_goals_desc: "Lisää ensimmäinen säästötavoitteesi.",
    progress: "Edistyminen",
    
    // Reports
    reports_title: "Raportit",
    reports_subtitle: "Taloutesi analytiikka",
    income: "Tulot",
    expenses: "Menot",
    savings_rate: "Säästöaste",
    daily_spending: "Päiväkulutus",
    tab_overview: "Yleiskuva",
    tab_categories: "Kategoriat",
    tab_trends: "Trendit",
    income_vs_expenses: "Tulot vs Menot",
    last_7_days: "Viimeisen 7 päivän kulutus",
    expense_distribution: "Kulujen jakautuminen",
    categories_breakdown: "Kategoriat eriteltynä",
    savings_goal: "Säästötavoite",
    saved_this_month: "Säästetty tässä kuussa",
    great_savings: "Loistavaa! Säästät hyvin!",
    save_20_percent: "Tavoite: säästä vähintään 20% tuloistasi",
    budget_usage: "Budjetin käyttö",
    tips: "Vinkkejä",
    tip_save_20: "Yritä säästää vähintään 20% tuloistasi kuukausittain",
    tip_budget_75: "Olet käyttänyt yli 75% budjetistasi - harkitse menojen vähentämistä",
    tip_pay_loans: "Maksa lainoja pois nopeammin säästääksesi korkokuluissa",
    tip_track: "Seuraa kulujasi säännöllisesti pysyäksesi budjetissa",
    no_data: "Ei vielä dataa",
    no_data_desc: "Lisää kuluja nähdäksesi kategorijakauman",
    
    // Banks
    banks_title: "Pankkiyhteydet",
    banks_subtitle: "Yhdistä pankkitilisi automaattiseen seurantaan",
    auto_tracking: "Automaattinen tilien seuranta",
    auto_tracking_desc: "Yhdistä pankkitilisi turvallisesti PSD2-standardin mukaisesti. Tapahtumat tuodaan automaattisesti Walletaan.",
    connected_banks: "Yhdistetyt pankit",
    connect_new_bank: "Yhdistä uusi pankki",
    no_banks: "Ei pankkeja saatavilla",
    bank_accounts: "Pankkitilit",
    select_account: "Valitse tili, josta haluat tuoda tapahtumat",
    balance: "Saldo",
    import_transactions: "Tuo tapahtumat",
    importing: "Tuodaan...",
    import_success: "Tuotiin {count} tapahtumaa",
    nordigen_not_configured: "Nordigen API ei ole konfiguroitu",
    nordigen_instructions: "Pankkiyhteydet vaativat Nordigen (GoCardless) API-avaimet. Noudata näitä ohjeita:",
    nordigen_step_1: "Luo ilmainen tili osoitteessa",
    nordigen_step_2: "Luo uudet \"User secrets\" hallintapaneelissa",
    nordigen_step_3: "Lisää NORDIGEN_SECRET_ID ja NORDIGEN_SECRET_KEY ympäristömuuttujiin",
    nordigen_step_4: "Käynnistä backend uudelleen",
    open_gocardless: "Avaa GoCardless",
    status_linked: "Yhdistetty",
    status_pending: "Odottaa",
    status_expired: "Vanhentunut",
    
    // Settings
    settings_title: "Asetukset",
    settings_subtitle: "Hallitse tiliäsi ja asetuksiasi",
    profile: "Profiili",
    account_created: "Tili luotu",
    subscription: "Tilaus",
    manage_subscription: "Hallitse tilaustasi",
    pro_active: "Pro-tilaus aktiivinen",
    subscription_valid_until: "Tilauksesi on voimassa {date} asti",
    upgrade_to_pro: "Päivitä Pro-tilaukseen",
    all_features: "Saat käyttöösi kaikki ominaisuudet",
    activate_subscription: "Aktivoi tilaus",
    notifications: "Ilmoitukset",
    notifications_desc: "Valitse mitä ilmoituksia saat",
    budget_alerts: "Budjettivaroitukset",
    budget_alerts_desc: "Saat ilmoituksen kun lähestyt budjettirajaa",
    weekly_report: "Viikkoraportti",
    weekly_report_desc: "Saat viikoittaisen yhteenvedon sähköpostilla",
    monthly_report: "Kuukausiraportti",
    monthly_report_desc: "Saat kuukausittaisen yhteenvedon sähköpostilla",
    security: "Turvallisuus",
    security_desc: "Hallitse tilisi turvallisuutta",
    change_password: "Vaihda salasana",
    change_password_desc: "Päivitä tilisi salasana",
    delete_account: "Poista tili",
    delete_account_desc: "Poista tilisi ja kaikki tietosi pysyvästi",
    language: "Kieli",
    
    // Payment
    payment: "Maksu",
    continue_to_payment: "Jatka maksuun",
    pay_with_card: "Maksa kortilla",
    skip_for_now: "Ohita ja kokeile ensin",
    payment_success: "Maksu onnistui!",
    payment_success_desc: "Kiitos tilauksestasi. Tilauksesi on nyt aktiivinen ja voit aloittaa Walletan käytön.",
    go_to_dashboard: "Siirry hallintapaneeliin",
    payment_failed: "Jotain meni pieleen",
    payment_failed_desc: "Emme pystyneet vahvistamaan maksuasi. Yritä uudelleen tai ota yhteyttä asiakaspalveluun.",
    try_again: "Yritä uudelleen",
    payment_cancelled: "Maksu peruutettu",
    payment_cancelled_desc: "Maksuprosessi keskeytettiin. Voit kokeilla uudelleen tai jatkaa Walletan käyttöä ilmaiseksi rajoitetuilla ominaisuuksilla.",
    continue_free: "Jatka ilmaiseksi",
    checking_payment: "Tarkistetaan maksua...",
    please_wait: "Odota hetki, vahvistamme maksusi.",
    
    // Categories
    cat_housing: "Asuminen",
    cat_food: "Ruoka",
    cat_transport: "Liikenne",
    cat_entertainment: "Viihde",
    cat_health: "Terveys",
    cat_clothing: "Vaatteet",
    cat_education: "Koulutus",
    cat_loans: "Lainat",
    cat_insurance: "Vakuutukset",
    cat_phone: "Puhelinliittymät",
    cat_other: "Muut",
    
    // Misc
    transactions: "tapahtumaa",
    per_month_short: "/kk",
    all_rights: "Kaikki oikeudet pidätetään.",
    unlimited_tracking: "Rajaton menoseuranta",
    budgeting_reports: "Budjetointi & raportit",
    secure_storage: "Turvallinen tietojen tallennus",
  },
  
  en: {
    // Common
    app_name: "Walleta",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    close: "Close",
    loading: "Loading...",
    refresh: "Refresh",
    back: "Back",
    next: "Next",
    yes: "Yes",
    no: "No",
    
    // Auth
    login: "Log in",
    logout: "Log out",
    register: "Sign up",
    email: "Email",
    password: "Password",
    name: "Name",
    login_title: "Welcome back",
    login_subtitle: "Log in to continue",
    register_title: "Create account",
    register_subtitle: "Start managing your finances today",
    no_account: "Don't have an account?",
    have_account: "Already have an account?",
    login_success: "Login successful!",
    register_success: "Account created successfully!",
    invalid_credentials: "Invalid email or password",
    
    // Landing
    hero_title: "Manage your finances",
    hero_title_highlight: "easily",
    hero_subtitle: "Walleta helps you understand, manage and improve your finances in everyday life – without stress or complexity.",
    start_now: "Start now",
    start_free: "Start for free",
    no_hidden_fees: "No hidden fees",
    cancel_anytime: "Cancel anytime",
    features_title: "Everything you need",
    features_subtitle: "Walleta gathers your financial data in one place and displays it in an understandable format",
    pricing_title: "Simple pricing",
    pricing_subtitle: "One price, all features. No hidden fees.",
    monthly_subscription: "Monthly subscription",
    per_month: "€ / mo",
    includes: "Includes:",
    cta_title: "Take control of your finances today",
    cta_subtitle: "Join thousands of users who already manage their finances with Walleta.",
    
    // Features
    budgeting: "Budgeting",
    budgeting_desc: "Set monthly budgets and track progress in real-time",
    expense_tracking: "Expense tracking",
    expense_tracking_desc: "Add expenses easily and group them by category",
    loan_management: "Loan management",
    loan_management_desc: "Track mortgages, car loans and other debts",
    savings_goals: "Savings goals",
    savings_goals_desc: "Set goals and track your progress",
    income_expenses: "Income & Expenses",
    income_expenses_desc: "See all your cash flows at a glance",
    secure: "Secure",
    secure_desc: "Your data is protected with strong encryption",
    
    // Navigation
    nav_overview: "Overview",
    nav_budget: "Budget",
    nav_expenses: "Expenses",
    nav_incomes: "Income",
    nav_loans: "Loans",
    nav_savings: "Savings",
    nav_reports: "Reports",
    nav_banks: "Banks",
    nav_settings: "Settings",
    
    // Dashboard
    dashboard_title: "Overview",
    dashboard_subtitle: "Your monthly financial summary",
    add_expense: "Add expense",
    monthly_expenses: "Monthly expenses",
    active_fixed_expenses: "Active fixed expenses",
    budget_used: "Budget used",
    budget: "Budget",
    income_remaining: "Income & Remaining",
    net_income_total: "Total net income",
    remaining: "Remaining",
    expenses_by_category: "Expenses by category",
    loans: "Loans",
    total_remaining: "Total remaining",
    monthly_payments: "Monthly payments",
    savings: "Savings",
    total_saved: "Total saved",
    target: "Target",
    net_worth: "Net worth",
    savings_minus_loans: "Savings - Loans",
    budget_alert_title: "Approaching budget limit",
    budget_alert_desc: "You have used {percentage} of your budget.",
    
    // Expenses
    expenses_title: "Expenses",
    expenses_subtitle: "Monthly expenses",
    add_new_expense: "Add new expense",
    amount: "Amount",
    description: "Description",
    category: "Category",
    date: "Date",
    select_category: "Select category",
    expense_added: "Expense added!",
    expense_deleted: "Expense deleted",
    no_expenses: "No expenses",
    no_expenses_desc: "Add your first expense to start tracking.",
    
    // Incomes
    incomes_title: "Income",
    incomes_subtitle: "Monthly income",
    add_income: "Add income",
    add_new_income: "Add new income",
    source: "Source",
    select_source: "Select source",
    recurring: "Recurring income",
    income_added: "Income added!",
    income_deleted: "Income deleted",
    no_incomes: "No income",
    no_incomes_desc: "Add your first income to start tracking.",
    source_salary: "Salary",
    source_freelance: "Freelance",
    source_investment: "Investments",
    source_other: "Other",
    
    // Budget
    budget_title: "Budget",
    set_budget: "Set budget",
    edit_budget: "Edit",
    monthly_budget: "Monthly budget",
    summary: "Summary",
    spent: "Spent",
    budget_remaining: "Remaining",
    usage_rate: "Usage rate",
    budget_saved: "Budget saved!",
    no_budget: "Set monthly budget",
    no_budget_desc: "Define your monthly budget to start tracking expenses.",
    
    // Loans
    loans_title: "Loans",
    loans_subtitle: "Manage your debts",
    add_loan: "Add loan",
    add_new_loan: "Add new loan",
    loan_name: "Loan name",
    loan_type: "Loan type",
    original_amount: "Original amount",
    remaining_amount: "Remaining",
    interest_rate: "Interest rate",
    monthly_payment: "Monthly payment",
    start_date: "Start date",
    loan_added: "Loan added!",
    loan_deleted: "Loan deleted",
    no_loans: "No loans",
    no_loans_desc: "Add a loan to start tracking debt.",
    paid: "Paid",
    loan_mortgage: "Mortgage",
    loan_car: "Car loan",
    loan_consumer: "Consumer loan",
    loan_student: "Student loan",
    
    // Savings
    savings_title: "Savings",
    savings_subtitle: "Track your savings goals",
    add_goal: "Add goal",
    add_savings_goal: "Add savings goal",
    goal_name: "Goal name",
    target_amount: "Target amount",
    current_amount: "Saved",
    target_date: "Target date",
    icon: "Icon",
    goal_added: "Savings goal added!",
    goal_updated: "Savings goal updated!",
    goal_deleted: "Savings goal deleted",
    no_goals: "No savings goals",
    no_goals_desc: "Add your first savings goal.",
    progress: "Progress",
    
    // Reports
    reports_title: "Reports",
    reports_subtitle: "Your financial analytics",
    income: "Income",
    expenses: "Expenses",
    savings_rate: "Savings rate",
    daily_spending: "Daily spending",
    tab_overview: "Overview",
    tab_categories: "Categories",
    tab_trends: "Trends",
    income_vs_expenses: "Income vs Expenses",
    last_7_days: "Last 7 days spending",
    expense_distribution: "Expense distribution",
    categories_breakdown: "Categories breakdown",
    savings_goal: "Savings goal",
    saved_this_month: "Saved this month",
    great_savings: "Great! You're saving well!",
    save_20_percent: "Goal: save at least 20% of your income",
    budget_usage: "Budget usage",
    tips: "Tips",
    tip_save_20: "Try to save at least 20% of your income monthly",
    tip_budget_75: "You've used over 75% of your budget - consider reducing expenses",
    tip_pay_loans: "Pay off loans faster to save on interest",
    tip_track: "Track your expenses regularly to stay on budget",
    no_data: "No data yet",
    no_data_desc: "Add expenses to see category breakdown",
    
    // Banks
    banks_title: "Bank connections",
    banks_subtitle: "Connect your bank account for automatic tracking",
    auto_tracking: "Automatic account tracking",
    auto_tracking_desc: "Connect your bank account securely via PSD2 standard. Transactions are automatically imported to Walleta.",
    connected_banks: "Connected banks",
    connect_new_bank: "Connect new bank",
    no_banks: "No banks available",
    bank_accounts: "Bank accounts",
    select_account: "Select account to import transactions from",
    balance: "Balance",
    import_transactions: "Import transactions",
    importing: "Importing...",
    import_success: "Imported {count} transactions",
    nordigen_not_configured: "Nordigen API not configured",
    nordigen_instructions: "Bank connections require Nordigen (GoCardless) API keys. Follow these instructions:",
    nordigen_step_1: "Create a free account at",
    nordigen_step_2: "Create new \"User secrets\" in the dashboard",
    nordigen_step_3: "Add NORDIGEN_SECRET_ID and NORDIGEN_SECRET_KEY to environment variables",
    nordigen_step_4: "Restart the backend",
    open_gocardless: "Open GoCardless",
    status_linked: "Linked",
    status_pending: "Pending",
    status_expired: "Expired",
    
    // Settings
    settings_title: "Settings",
    settings_subtitle: "Manage your account and preferences",
    profile: "Profile",
    account_created: "Account created",
    subscription: "Subscription",
    manage_subscription: "Manage your subscription",
    pro_active: "Pro subscription active",
    subscription_valid_until: "Your subscription is valid until {date}",
    upgrade_to_pro: "Upgrade to Pro",
    all_features: "Get access to all features",
    activate_subscription: "Activate subscription",
    notifications: "Notifications",
    notifications_desc: "Choose which notifications you receive",
    budget_alerts: "Budget alerts",
    budget_alerts_desc: "Get notified when approaching budget limit",
    weekly_report: "Weekly report",
    weekly_report_desc: "Receive weekly summary via email",
    monthly_report: "Monthly report",
    monthly_report_desc: "Receive monthly summary via email",
    security: "Security",
    security_desc: "Manage your account security",
    change_password: "Change password",
    change_password_desc: "Update your account password",
    delete_account: "Delete account",
    delete_account_desc: "Permanently delete your account and all data",
    language: "Language",
    
    // Payment
    payment: "Payment",
    continue_to_payment: "Continue to payment",
    pay_with_card: "Pay with card",
    skip_for_now: "Skip and try first",
    payment_success: "Payment successful!",
    payment_success_desc: "Thank you for your subscription. Your subscription is now active and you can start using Walleta.",
    go_to_dashboard: "Go to dashboard",
    payment_failed: "Something went wrong",
    payment_failed_desc: "We couldn't verify your payment. Please try again or contact support.",
    try_again: "Try again",
    payment_cancelled: "Payment cancelled",
    payment_cancelled_desc: "The payment process was cancelled. You can try again or continue using Walleta for free with limited features.",
    continue_free: "Continue for free",
    checking_payment: "Checking payment...",
    please_wait: "Please wait while we verify your payment.",
    
    // Categories
    cat_housing: "Housing",
    cat_food: "Food",
    cat_transport: "Transport",
    cat_entertainment: "Entertainment",
    cat_health: "Health",
    cat_clothing: "Clothing",
    cat_education: "Education",
    cat_loans: "Loans",
    cat_insurance: "Insurance",
    cat_phone: "Phone",
    cat_other: "Other",
    
    // Misc
    transactions: "transactions",
    per_month_short: "/mo",
    all_rights: "All rights reserved.",
    unlimited_tracking: "Unlimited expense tracking",
    budgeting_reports: "Budgeting & reports",
    secure_storage: "Secure data storage",
  }
};

const LanguageContext = createContext(null);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem("walleta_language");
    return saved || "fi";
  });

  useEffect(() => {
    localStorage.setItem("walleta_language", language);
  }, [language]);

  const t = (key, params = {}) => {
    let text = translations[language]?.[key] || translations.fi[key] || key;
    
    // Replace parameters like {percentage}
    Object.keys(params).forEach(param => {
      text = text.replace(`{${param}}`, params[param]);
    });
    
    return text;
  };

  const toggleLanguage = () => {
    setLanguage(prev => prev === "fi" ? "en" : "fi");
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
